(cl:defpackage swarm_control_package-srv
  (:use )
  (:export
   "NEWTARGET"
   "<NEWTARGET-REQUEST>"
   "NEWTARGET-REQUEST"
   "<NEWTARGET-RESPONSE>"
   "NEWTARGET-RESPONSE"
   "SPECIALCOMMANDS"
   "<SPECIALCOMMANDS-REQUEST>"
   "SPECIALCOMMANDS-REQUEST"
   "<SPECIALCOMMANDS-RESPONSE>"
   "SPECIALCOMMANDS-RESPONSE"
  ))

