// Generated by gencpp from file swarm_control_package/NewTarget.msg
// DO NOT EDIT!


#ifndef SWARM_CONTROL_PACKAGE_MESSAGE_NEWTARGET_H
#define SWARM_CONTROL_PACKAGE_MESSAGE_NEWTARGET_H

#include <ros/service_traits.h>


#include <swarm_control_package/NewTargetRequest.h>
#include <swarm_control_package/NewTargetResponse.h>


namespace swarm_control_package
{

struct NewTarget
{

typedef NewTargetRequest Request;
typedef NewTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NewTarget
} // namespace swarm_control_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::swarm_control_package::NewTarget > {
  static const char* value()
  {
    return "02e92aea6f3587911e71e635adcba734";
  }

  static const char* value(const ::swarm_control_package::NewTarget&) { return value(); }
};

template<>
struct DataType< ::swarm_control_package::NewTarget > {
  static const char* value()
  {
    return "swarm_control_package/NewTarget";
  }

  static const char* value(const ::swarm_control_package::NewTarget&) { return value(); }
};


// service_traits::MD5Sum< ::swarm_control_package::NewTargetRequest> should match
// service_traits::MD5Sum< ::swarm_control_package::NewTarget >
template<>
struct MD5Sum< ::swarm_control_package::NewTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::swarm_control_package::NewTarget >::value();
  }
  static const char* value(const ::swarm_control_package::NewTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::swarm_control_package::NewTargetRequest> should match
// service_traits::DataType< ::swarm_control_package::NewTarget >
template<>
struct DataType< ::swarm_control_package::NewTargetRequest>
{
  static const char* value()
  {
    return DataType< ::swarm_control_package::NewTarget >::value();
  }
  static const char* value(const ::swarm_control_package::NewTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::swarm_control_package::NewTargetResponse> should match
// service_traits::MD5Sum< ::swarm_control_package::NewTarget >
template<>
struct MD5Sum< ::swarm_control_package::NewTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::swarm_control_package::NewTarget >::value();
  }
  static const char* value(const ::swarm_control_package::NewTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::swarm_control_package::NewTargetResponse> should match
// service_traits::DataType< ::swarm_control_package::NewTarget >
template<>
struct DataType< ::swarm_control_package::NewTargetResponse>
{
  static const char* value()
  {
    return DataType< ::swarm_control_package::NewTarget >::value();
  }
  static const char* value(const ::swarm_control_package::NewTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SWARM_CONTROL_PACKAGE_MESSAGE_NEWTARGET_H
