// Generated by gencpp from file swarm_control_package/SpecialCommandsResponse.msg
// DO NOT EDIT!


#ifndef SWARM_CONTROL_PACKAGE_MESSAGE_SPECIALCOMMANDSRESPONSE_H
#define SWARM_CONTROL_PACKAGE_MESSAGE_SPECIALCOMMANDSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_control_package
{
template <class ContainerAllocator>
struct SpecialCommandsResponse_
{
  typedef SpecialCommandsResponse_<ContainerAllocator> Type;

  SpecialCommandsResponse_()
    : Response()  {
    }
  SpecialCommandsResponse_(const ContainerAllocator& _alloc)
    : Response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Response_type;
  _Response_type Response;





  typedef boost::shared_ptr< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SpecialCommandsResponse_

typedef ::swarm_control_package::SpecialCommandsResponse_<std::allocator<void> > SpecialCommandsResponse;

typedef boost::shared_ptr< ::swarm_control_package::SpecialCommandsResponse > SpecialCommandsResponsePtr;
typedef boost::shared_ptr< ::swarm_control_package::SpecialCommandsResponse const> SpecialCommandsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator1> & lhs, const ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Response == rhs.Response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator1> & lhs, const ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_control_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9ca8778f2b24ad03f8213b9fe82be44";
  }

  static const char* value(const ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9ca8778f2b24ad0ULL;
  static const uint64_t static_value2 = 0x3f8213b9fe82be44ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_control_package/SpecialCommandsResponse";
  }

  static const char* value(const ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Response\n"
"\n"
"\n"
;
  }

  static const char* value(const ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpecialCommandsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_control_package::SpecialCommandsResponse_<ContainerAllocator>& v)
  {
    s << indent << "Response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_CONTROL_PACKAGE_MESSAGE_SPECIALCOMMANDSRESPONSE_H
