// Generated by gencpp from file swarm_control_package/SpecialCommands.msg
// DO NOT EDIT!


#ifndef SWARM_CONTROL_PACKAGE_MESSAGE_SPECIALCOMMANDS_H
#define SWARM_CONTROL_PACKAGE_MESSAGE_SPECIALCOMMANDS_H

#include <ros/service_traits.h>


#include <swarm_control_package/SpecialCommandsRequest.h>
#include <swarm_control_package/SpecialCommandsResponse.h>


namespace swarm_control_package
{

struct SpecialCommands
{

typedef SpecialCommandsRequest Request;
typedef SpecialCommandsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpecialCommands
} // namespace swarm_control_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::swarm_control_package::SpecialCommands > {
  static const char* value()
  {
    return "a1be574ae7cc4fce751bea7c600387df";
  }

  static const char* value(const ::swarm_control_package::SpecialCommands&) { return value(); }
};

template<>
struct DataType< ::swarm_control_package::SpecialCommands > {
  static const char* value()
  {
    return "swarm_control_package/SpecialCommands";
  }

  static const char* value(const ::swarm_control_package::SpecialCommands&) { return value(); }
};


// service_traits::MD5Sum< ::swarm_control_package::SpecialCommandsRequest> should match
// service_traits::MD5Sum< ::swarm_control_package::SpecialCommands >
template<>
struct MD5Sum< ::swarm_control_package::SpecialCommandsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::swarm_control_package::SpecialCommands >::value();
  }
  static const char* value(const ::swarm_control_package::SpecialCommandsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::swarm_control_package::SpecialCommandsRequest> should match
// service_traits::DataType< ::swarm_control_package::SpecialCommands >
template<>
struct DataType< ::swarm_control_package::SpecialCommandsRequest>
{
  static const char* value()
  {
    return DataType< ::swarm_control_package::SpecialCommands >::value();
  }
  static const char* value(const ::swarm_control_package::SpecialCommandsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::swarm_control_package::SpecialCommandsResponse> should match
// service_traits::MD5Sum< ::swarm_control_package::SpecialCommands >
template<>
struct MD5Sum< ::swarm_control_package::SpecialCommandsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::swarm_control_package::SpecialCommands >::value();
  }
  static const char* value(const ::swarm_control_package::SpecialCommandsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::swarm_control_package::SpecialCommandsResponse> should match
// service_traits::DataType< ::swarm_control_package::SpecialCommands >
template<>
struct DataType< ::swarm_control_package::SpecialCommandsResponse>
{
  static const char* value()
  {
    return DataType< ::swarm_control_package::SpecialCommands >::value();
  }
  static const char* value(const ::swarm_control_package::SpecialCommandsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SWARM_CONTROL_PACKAGE_MESSAGE_SPECIALCOMMANDS_H
